#!/bin/sh

[[ "$ACTION" != ifup ]] && exit 0;
[[ "$( uci get wireless.$INTERFACE.mode 2>/dev/null )" != mesh ]] && exit 0;

local POLICY=$( uci get wireless.$INTERFACE.macfilter 2>/dev/null )
	
case $POLICY in
	deny)	local IW_POLICY="block";;
	allow)	local IW_POLICY="open"; iw dev $DEVICE set mesh_param mesh_auto_open_plink=0;;
	*) 		exit 0;;
esac

for MAC in $( uci get wireless.$INTERFACE.maclist 2>/dev/null ); do
	iw dev $DEVICE station set $MAC plink_action $IW_POLICY
done
